### ISSUE TITLE
Content arrangement

### ISSUE THREAD

**Issue by krainboltgreene** [PolymerElements/paper-progress#14]
Often times the UI will need to accommodate text inside the progress bar, adjacent to the progress bar, above, or under.

Currently it doesn't seem to accommodate any of these well?

**Comment by blasten** [comment]
No. I'm not sure why paper-progress should take care of this issue. Can you give me an example?

**Comment by krainboltgreene** [comment]
http://getbootstrap.com/components/#progress-label
http://zurb.com/building-blocks/dashboard-control-tabs
http://semantic-ui.com/modules/progress.html
http://concisecss.com/add-ons/progress-bars/

**Comment by blasten** [comment]
We currently don't support that use case, but you can use an `iron-range-behavior` for that case: https://github.com/PolymerElements/iron-range-behavior.

https://elements.polymer-project.org/elements/iron-range-behavior?view=demo:demo/index.html&active=Polymer.IronRangeBehavior

**Comment by krainboltgreene** [comment]
Yes, I know you don't, this is a feature suggestion.

**Comment by blasten** [comment]
sounds good to me.

**Comment by keanulee** [comment]
The material design spec (https://www.google.com/design/spec/components/progress-activity.html) does not suggest having text inside the progress bar. Because the paper elements tries to adhere to those specifications, there is no supported way to add text within the bar. For custom styling, please use https://elements.polymer-project.org/elements/iron-range-behavior.
